void inf ();
int menu ();
void noValido ();
char* salir (char resp[10]);
int numObjAñadir (int indexFinal);
char* añadirNombre(int index, char nombres[][20]);
float añadirDatos (int a,int index, char nombres[][20]);
int indexEditar (char nombres[][20]);
char* editarNombre (int index, char nombres[][20],float datos [][2]);
float editarCantidad (int index, float datos[][2]);
int comprobarReplicas (char nombres[][20],int index);
float validarNum (int insp);
int indexEliminar (char nombres[][20]);
char* vaciarStr (int index,char str[][20]);
char* reordenarNombre (int i,char nombres[][20]);
void imprimirTabla(char nombres [][20], char vacio[], float datos [][2]);
float reordenarDatos(int inicio,float datos[][2],int j);
int comprobarVacio (char arreglo[][20],char vacio[]);